In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
df=pd.read_csv("C:/Users/arohi/.jupyter/melb_data.csv")

In [3]:
df.head()

Suburb           Address  Rooms Type    Price Method SellerG  \
0  Abbotsford      85 Turner St      2    h  1480000      S  Biggin   
1  Abbotsford   25 Bloomburg St      2    h  1035000      S  Biggin   
2  Abbotsford      5 Charles St      3    h  1465000     SP  Biggin   
3  Abbotsford  40 Federation La      3    h   850000     PI  Biggin   
4  Abbotsford       55a Park St      4    h  1600000     VB  Nelson   

         Date  Distance  Postcode  ...  Bathroom  Car  Landsize  BuildingArea  \
0  03-12-2016       2.5      3067  ...         1  1.0       202           NaN   
1  04-02-2016       2.5      3067  ...         1  0.0       156          79.0   
2  04-03-2017       2.5      3067  ...         2  0.0       134         150.0   
3  04-03-2017       2.5      3067  ...         2  1.0        94           NaN   
4  04-06-2016       2.5      3067  ...         1  2.0       120         142.0   

   YearBuilt  CouncilArea Lattitude  Longtitude             Regionname  \
0        NaN        Yarra  -37.7996    144.9984  Northern Metropolitan   
1     1900.0        Yarra  -37.8079    144.9934  Northern Metropolitan   
2     1900.0        Yarra  -37.8093    144.9944  Northern Metropolitan   
3        NaN        Yarra  -37.7969    144.9969  Northern Metropolitan   
4     2014.0        Yarra  -37.8072    144.9941  Northern Metropolitan   

  Propertycount  
0          4019  
1          4019  
2          4019  
3          4019  
4          4019  

[5 rows x 21 columns]

In [10]:
df.shape

(13580, 21)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13580 entries, 0 to 13579
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Suburb         13580 non-null  object 
 1   Address        13580 non-null  object 
 2   Rooms          13580 non-null  int64  
 3   Type           13580 non-null  object 
 4   Price          13580 non-null  int64  
 5   Method         13580 non-null  object 
 6   SellerG        13580 non-null  object 
 7   Date           13580 non-null  object 
 8   Distance       13580 non-null  float64
 9   Postcode       13580 non-null  int64  
 10  Bedroom2       13580 non-null  int64  
 11  Bathroom       13580 non-null  int64  
 12  Car            13518 non-null  float64
 13  Landsize       13580 non-null  int64  
 14  BuildingArea   7130 non-null   float64
 15  YearBuilt      8205 non-null   float64
 16  CouncilArea    12211 non-null  object 
 17  Lattitude      13580 non-null  float64
 18  Longti

In [11]:
#check null value
df.isnull().sum()

Suburb              0
Address             0
Rooms               0
Type                0
Price               0
Method              0
SellerG             0
Date                0
Distance            0
Postcode            0
Bedroom2            0
Bathroom            0
Car                62
Landsize            0
BuildingArea     6450
YearBuilt        5375
CouncilArea      1369
Lattitude           0
Longtitude          0
Regionname          0
Propertycount       0
dtype: int64

In [25]:
df["BuildingArea"].unique()   

array([         nan, 7.900000e+01, 1.500000e+02, 1.420000e+02,
       2.100000e+02, 1.070000e+02, 7.500000e+01, 1.900000e+02,
       9.400000e+01, 9.700000e+01, 1.100000e+02, 1.050000e+02,
       7.300000e+01, 1.350000e+02, 2.700000e+01, 6.000000e+01,
       8.500000e+01, 1.740000e+02, 5.000000e+01, 1.280000e+02,
       1.800000e+01, 1.240000e+02, 9.100000e+01, 8.200000e+01,
       8.100000e+01, 2.250000e+02, 1.450000e+02, 8.400000e+01,
       1.340000e+02, 1.160000e+02, 8.600000e+01, 1.270000e+02,
       1.860000e+02, 9.000000e+01, 1.330000e+02, 1.300000e+02,
       1.130000e+02, 1.000000e+02, 3.090000e+02, 1.920000e+02,
       1.260000e+02, 1.010000e+02, 1.020000e+02, 7.600000e+01,
       1.460000e+02, 1.980000e+02, 1.800000e+02, 1.590000e+02,
       1.220000e+02, 1.810000e+02, 9.800000e+01, 8.300000e+01,
       1.470000e+02, 2.540000e+02, 1.230000e+02, 1.310000e+02,
       3.400000e+01, 2.070000e+02, 6.800000e+01, 5.400000e+01,
       2.630000e+02, 2.030000e+02, 1.650000e+02, 1.4000

In [30]:
df["BuildingArea"].replace("?",np.nan,inplace=True) #change permanenetly
#type change permanently

In [26]:
df["YearBuilt"].unique() 

array([  nan, 1900., 2014., 1910., 1890., 2005., 2009., 1880., 1985.,
       2010., 1970., 2013., 2012., 1920., 1950., 1998., 1930., 2016.,
       1965., 1980., 2011., 2015., 1975., 1993., 1960., 2003., 1995.,
       1996., 2000., 1925., 2004., 2008., 1962., 1955., 1988., 1953.,
       1997., 1990., 2007., 1967., 1964., 1889., 1888., 2006., 1934.,
       1935., 1966., 1969., 1940., 1938., 1887., 1904., 1972., 1978.,
       1939., 1945., 1947., 1958., 2017., 1999., 1992., 1961., 1928.,
       1977., 1976., 2001., 1948., 1927., 1981., 1943., 1974., 1968.,
       1957., 1987., 1986., 1926., 2002., 1994., 1949., 1905., 1912.,
       1924., 1952., 1991., 1942., 1973., 1915., 2018., 1916., 1982.,
       1971., 1963., 1897., 1989., 1919., 1923., 1983., 1903., 1830.,
       1895., 1937., 1908., 1913., 1917., 1885., 1902., 1854., 1850.,
       1898., 1941., 1951., 1946., 1956., 1984., 1901., 1959., 1979.,
       1933., 1886., 1929., 1906., 1870., 1932., 1875., 1863., 1918.,
       1893., 1856.,

In [31]:
df["YearBuilt"].replace("?",np.nan,inplace=True) #change permanenetly
#type change permanently

In [28]:
df.CouncilArea.unique()

array(['Yarra', 'Moonee Valley', 'Port Phillip', 'Darebin', 'Hobsons Bay',
       'Stonnington', 'Boroondara', 'Monash', 'Glen Eira', 'Whitehorse',
       'Maribyrnong', 'Bayside', 'Moreland', 'Manningham', 'Banyule',
       'Melbourne', 'Kingston', 'Brimbank', 'Hume', nan, 'Knox',
       'Maroondah', 'Casey', 'Melton', 'Greater Dandenong', 'Nillumbik',
       'Whittlesea', 'Frankston', 'Macedon Ranges', 'Yarra Ranges',
       'Wyndham', 'Cardinia', 'Unavailable', 'Moorabool'], dtype=object)

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 13580 entries, 0 to 13579
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Suburb         13580 non-null  object 
 1   Address        13580 non-null  object 
 2   Rooms          13580 non-null  int64  
 3   Type           13580 non-null  object 
 4   Price          13580 non-null  int64  
 5   Method         13580 non-null  object 
 6   SellerG        13580 non-null  object 
 7   Date           13580 non-null  object 
 8   Distance       13580 non-null  float64
 9   Postcode       13580 non-null  int64  
 10  Bedroom2       13580 non-null  int64  
 11  Bathroom       13580 non-null  int64  
 12  Car            13518 non-null  float64
 13  Landsize       13580 non-null  int64  
 14  BuildingArea   7130 non-null   float64
 15  YearBuilt      8205 non-null   float64
 16  CouncilArea    12211 non-null  object 
 17  Lattitude      13580 non-null  float64
 18  Longti

In [33]:
df["BuildingArea"].fillna(df["BuildingArea"].mean(),inplace=True)

In [34]:
df["YearBuilt"].fillna(df["YearBuilt"].mean(),inplace=True)

In [38]:
df.isnull().sum()

Suburb              0
Address             0
Rooms               0
Type                0
Price               0
Method              0
SellerG             0
Date                0
Distance            0
Postcode            0
Bedroom2            0
Bathroom            0
Car                62
Landsize            0
BuildingArea        0
YearBuilt           0
CouncilArea      1369
Lattitude           0
Longtitude          0
Regionname          0
Propertycount       0
dtype: int64

In [39]:
df["Car"].fillna(df["Car"].mean(),inplace=True)

In [40]:
df.shape

(13580, 21)

In [41]:
Mode_Category = df.CouncilArea.mode()[0]

In [42]:
df["CouncilArea"].fillna(Mode_Category,inplace=True)

In [43]:
df.isnull().sum()

Suburb           0
Address          0
Rooms            0
Type             0
Price            0
Method           0
SellerG          0
Date             0
Distance         0
Postcode         0
Bedroom2         0
Bathroom         0
Car              0
Landsize         0
BuildingArea     0
YearBuilt        0
CouncilArea      0
Lattitude        0
Longtitude       0
Regionname       0
Propertycount    0
dtype: int64

In [44]:
#separate numerical type column and object type column and store in new dataset
df_num=df.select_dtypes(["int64","float64"])
df_cat=df.select_dtypes(object)

In [45]:
#change the object type data into numerical type then use LabelEncoder class
from sklearn.preprocessing import LabelEncoder

In [46]:
for col in df_cat :
    le=LabelEncoder() #create the object of LabelEncoder class
    df_cat[col]=le.fit_transform(df_cat[col])

In [47]:
df_cat.head()

Suburb  Address  Type  Method  SellerG  Date  CouncilArea  Regionname
0       0    12794     0       1       23     4           31           2
1       0     5943     0       1       23     5           31           2
2       0     9814     0       3       23     6           31           2
3       0     9004     0       0       23     6           31           2
4       0    10589     0       4      155     7           31           2

In [48]:
#concatenation of both dataset df_num and df_cat and hold new dataset df_new
df_new=pd.concat([df_num,df_cat],axis=1)

In [49]:
df_new.head()

Rooms    Price  Distance  Postcode  Bedroom2  Bathroom  Car  Landsize  \
0      2  1480000       2.5      3067         2         1  1.0       202   
1      2  1035000       2.5      3067         2         1  0.0       156   
2      3  1465000       2.5      3067         3         2  0.0       134   
3      3   850000       2.5      3067         3         2  1.0        94   
4      4  1600000       2.5      3067         3         1  2.0       120   

   BuildingArea    YearBuilt  ...  Longtitude  Propertycount  Suburb  Address  \
0     151.96765  1964.684217  ...    144.9984           4019       0    12794   
1      79.00000  1900.000000  ...    144.9934           4019       0     5943   
2     150.00000  1900.000000  ...    144.9944           4019       0     9814   
3     151.96765  1964.684217  ...    144.9969           4019       0     9004   
4     142.00000  2014.000000  ...    144.9941           4019       0    10589   

   Type  Method  SellerG  Date  CouncilArea  Regionname  
0     0       1       23     4           31           2  
1     0       1       23     5           31           2  
2     0       3       23     6           31           2  
3     0       0       23     6           31           2  
4     0       4      155     7           31           2  

[5 rows x 21 columns]

In [50]:
#select X and Y means input and output from dataset df_new
X=df_new.drop("Price",axis=1)
Y=df_new["Price"]#target variable

In [51]:
#train_test_split
from sklearn.model_selection import train_test_split

In [53]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=1)

In [54]:
from sklearn.linear_model import LinearRegression

In [55]:
#perform this dataset from linear regression
#create the object of LinearRegression
lr=LinearRegression()

In [56]:
#train the model
lr.fit(X_train,Y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [57]:
#check training score after train the model
lr.score(X_train,Y_train)

0.5783169230877807

In [58]:
#testing score
lr.score(X_test,Y_test)

0.5910828693255014

In [59]:
from sklearn.linear_model import Lasso #lambda*sumof(abs(all coefficient))

In [60]:
#create object of Lasso class
#range of lambda/alpha (hyper parameter ) 200-1000
l1=Lasso(1000)#pass value of lambda 

In [61]:
l1.fit(X_train,Y_train)

Lasso(alpha=1000, copy_X=True, fit_intercept=True, max_iter=1000,
      normalize=False, positive=False, precompute=False, random_state=None,
      selection='cyclic', tol=0.0001, warm_start=False)

In [62]:
#How to select the right value of lambda/alpha   in Lasso regularization
for i in range(200,1001,50) :  #start=200 stop=1001-1=1000 and step=+50
    #create object of Lasso
    l1=Lasso(i)
    #train
    l1.fit(X_train,Y_train)
    print("Value of Lambda : ",i," Score : ",l1.score(X_test,Y_test))

Value of Lambda :  200  Score :  0.5910338913828524
Value of Lambda :  250  Score :  0.5910125533416499
Value of Lambda :  300  Score :  0.590987585352988
Value of Lambda :  350  Score :  0.5909589789993064
Value of Lambda :  400  Score :  0.5909267341247693
Value of Lambda :  450  Score :  0.5908908505543956
Value of Lambda :  500  Score :  0.590851344679796
Value of Lambda :  550  Score :  0.5908081851414488
Value of Lambda :  600  Score :  0.5907614050948587
Value of Lambda :  650  Score :  0.5907109693729599
Value of Lambda :  700  Score :  0.5906569151568957
Value of Lambda :  750  Score :  0.5905992030097088
Value of Lambda :  800  Score :  0.5905378746269938
Value of Lambda :  850  Score :  0.5904729091479064
Value of Lambda :  900  Score :  0.5904043065724742
Value of Lambda :  950  Score :  0.5903320435945936
Value of Lambda :  1000  Score :  0.5902561668556399


In [63]:
from sklearn.linear_model import Ridge #lambda*sumof(sqr(all coefficient))

In [64]:
#call class
from sklearn.model_selection import cross_val_score
#cross_val_score inbuilt clas

In [65]:
#Create the object of Lasso and Ridge regularization
l1=Lasso(200) #passing the value of lambda=200
l2=Ridge(2) #passing  the value of lambda/alpha=

In [68]:
#apply cross validation on lasso regularisztion
#create the object of cross_val_score
l1_cross=cross_val_score(l1,X,Y,cv=4) #cv means how many folds means how many 
#parts or iteration

In [69]:
#check l1_cross
l1_cross

array([0.61555259, 0.57669199, 0.57805242, 0.15601844])

In [70]:
#apply cross validation onRTidge regularisztion
#create the object of cross_val_score
l2_cross=cross_val_score(l2,X,Y,cv=4) #cv means how many folds means how many 
#parts or iteration

In [71]:
#check
l2_cross

array([0.61563437, 0.5767858 , 0.57814793, 0.15687281])

In [73]:
#find the mean means average
np.mean(l2_cross)

0.48186022884533697